In [ ]:
dict 
csv  ->

In [ ]:
types :
    normal file -- text file 
        values comma separated values
    tsv - tab separated values

In [ ]:
text.xlsx
text.pdf



extension :

In [ ]:
we fetch -- data -- dataframe

In [ ]:
web crawling : web scrapping : 
        
        
        
        python -- web site --> scrap

In [1]:
import pandas as pd

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/COVID-19_pandemic_by_country_and_territory')

In [16]:
df[12]

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],870,6945701,768186332
1,NaN,Peru,6484,220793,4508103
2,NaN,Bulgaria,5663,38412,1308683
3,NaN,Bosnia and Herzegovina,5056,16350,403041
4,NaN,Hungary,4895,48795,2203082
...,...,...,...,...,...
235,NaN,Tuvalu,—,—,2911
236,NaN,Tokelau,—,0,5
237,NaN,Niue,—,—,820
238,NaN,"Saint Helena, Ascension and Tristan da Cunha",—,—,2166
239,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...

In [ ]:
5.Dataframe using api

In [21]:
df2 = pd.read_json('https://dummyjson.com/products')

In [23]:
df2['products']

0     {'id': 1, 'title': 'iPhone 9', 'description': ...
1     {'id': 2, 'title': 'iPhone X', 'description': ...
2     {'id': 3, 'title': 'Samsung Universe 9', 'desc...
3     {'id': 4, 'title': 'OPPOF19', 'description': '...
4     {'id': 5, 'title': 'Huawei P30', 'description'...
5     {'id': 6, 'title': 'MacBook Pro', 'description...
6     {'id': 7, 'title': 'Samsung Galaxy Book', 'des...
7     {'id': 8, 'title': 'Microsoft Surface Laptop 4...
8     {'id': 9, 'title': 'Infinix INBOOK', 'descript...
9     {'id': 10, 'title': 'HP Pavilion 15-DK1056WM',...
10    {'id': 11, 'title': 'perfume Oil', 'descriptio...
11    {'id': 12, 'title': 'Brown Perfume', 'descript...
12    {'id': 13, 'title': 'Fog Scent Xpressio Perfum...
13    {'id': 14, 'title': 'Non-Alcoholic Concentrate...
14    {'id': 15, 'title': 'Eau De Perfume Spray', 'd...
15    {'id': 16, 'title': 'Hyaluronic Acid Serum', '...
16    {'id': 17, 'title': 'Tree Oil 30ml', 'descript...
17    {'id': 18, 'title': 'Oil Free Moisturizer 100m...
18    {'id': 19, 'title': 'Skin Beauty Serum.', 'des...
19    {'id': 20, 'title': 'Freckle Treatment Cream- ...
20    {'id': 21, 'title': '- Daal Masoor 500 grams',...
21    {'id': 22, 'title': 'Elbow Macaroni - 400 gm',...
22    {'id': 23, 'title': 'Orange Essence Food Flavo...
23    {'id': 24, 'title': 'cereals muesli fruit nuts...
24    {'id': 25, 'title': 'Gulab Powder 50 Gram', 'd...
25    {'id': 26, 'title': 'Plant Hanger For Home', '...
26    {'id': 27, 'title': 'Flying Wooden Bird', 'des...
27    {'id': 28, 'title': '3D Embellishment Art Lamp...
28    {'id': 29, 'title': 'Handcraft Chinese style',...
29    {'id': 30, 'title': 'Key Holder', 'description...
Name: products, dtype: object

In [24]:
df4 = pd.read_json('https://dummy.restapiexample.com/api/v1/employees')

HTTPError: HTTP Error 406: Not Acceptable

In [25]:
df = pd.read_csv('Amazon_Car_Accessories - Amazon_Car_Accessories.csv')

In [26]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [27]:
df.shape

(9573, 9)

In [28]:
df.columns

Index(['Title', 'Price', 'Number reviews', 'Real price', 'Free days',
       'Shipment', 'Delivery Date', 'How many time in past month',
       'Stock update'],
      dtype='object')

In [30]:
df.dtypes

Title                          object
Price                          object
Number reviews                 object
Real price                     object
Free days                      object
Shipment                       object
Delivery Date                  object
How many time in past month    object
Stock update                   object
dtype: object

In [ ]:
python   char/str --string

pandas --char/str -->object

In [ ]:
email --> file - sharepoint  --> database -- api

In [31]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [32]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [33]:
df['Price']

0       35
1       19
2       13
3        2
4        8
        ..
9568    76
9569     7
9570    71
9571    35
9572    26
Name: Price, Length: 9573, dtype: object

In [34]:
df.Price

0       35
1       19
2       13
3        2
4        8
        ..
9568    76
9569     7
9570    71
9571    35
9572    26
Name: Price, Length: 9573, dtype: object

In [ ]:
col name --no space  -- both method

col name -- if space -->

In [35]:
df.Number reviews

SyntaxError: invalid syntax (4255864828.py, line 1)

In [36]:
df['Number reviews']

0          101
1          386
2        1,573
3            9
4       20,378
         ...
9568        11
9569         5
9570         5
9571         5
9572         5
Name: Number reviews, Length: 9573, dtype: object

In [38]:
df1= df[['Title','Price','Shipment']]

In [41]:
df1.to_csv('test.csv')

In [43]:
df1.to_excel('test.xlsx',index=False)

In [45]:
df1.to_html(r'C:\Users\kanti\OneDrive\Desktop\mypythonproject\test.html')

In [46]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [47]:
df.columns

Index(['Title', 'Price', 'Number reviews', 'Real price', 'Free days',
       'Shipment', 'Delivery Date', 'How many time in past month',
       'Stock update'],
      dtype='object')

In [ ]:
manually --> time

In [51]:
cols = []
for col in df.columns:
    if col not in ['Free days','Price','Title']:
        cols.append(col)

In [52]:
cols

['Number reviews',
 'Real price',
 'Shipment',
 'Delivery Date',
 'How many time in past month',
 'Stock update']

In [53]:
df[cols]

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [ ]:
100 -- 5  --> python code

In [56]:
df3 = df[[col for col in df.columns  if col not in ['Free days','Price','Title']]]

In [ ]:
df -- new col add

In [55]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [60]:
df3['test'] = df['Number reviews']*2

C:\Users\kanti\AppData\Local\Temp\ipykernel_10328\4272261182.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['test'] = df['Number reviews']*2

In [61]:
df3

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update,test
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.,101101
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).,386386
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).,"1,5731,573"
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.,99
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.,"20,37820,378"
...,...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,1111
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55

In [62]:
df3['lenofStock update'] =  len(df3['Stock update'])

C:\Users\kanti\AppData\Local\Temp\ipykernel_10328\2810776397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['lenofStock update'] =  len(df3['Stock update'])

In [63]:
df3

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update,test,lenofStock update
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.,101101,9573
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).,386386,9573
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).,"1,5731,573",9573
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.,99,9573
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.,"20,37820,378",9573
...,...,...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,1111,9573
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573

In [64]:
df['Stock update']

0             Only 7 left in stock - order soon.
1        Only 4 left in stock (more on the way).
2       Only 16 left in stock (more on the way).
3             Only 3 left in stock - order soon.
4             Only 2 left in stock - order soon.
                          ...
9568    Only 17 left in stock (more on the way).
9569    Only 17 left in stock (more on the way).
9570    Only 17 left in stock (more on the way).
9571    Only 17 left in stock (more on the way).
9572    Only 17 left in stock (more on the way).
Name: Stock update, Length: 9573, dtype: object

In [66]:
len(df3['Stock update'])

9573

In [70]:
len('Only 7 left in stock - order soon.')

34

In [72]:
df3['newcolname'] = 'asdfsadf'

In [73]:
df3

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update,test,lenofStock update,len_temp,newcolname
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.,101101,9573,34,asdfsadf
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).,386386,9573,39,asdfsadf
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).,"1,5731,573",9573,40,asdfsadf
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.,99,9573,34,asdfsadf
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.,"20,37820,378",9573,34,asdfsadf
...,...,...,...,...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,1111,9573,40,asdfsadf
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573,40,asdfsadf
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573,40,asdfsadf
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573,40,asdfsadf
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,55,9573,40,asdfsadf

In [ ]:
col -- delete from dataframe

In [78]:
df4 = df3.drop('test',axis=1)

In [ ]:
axis -->

In [79]:
df4

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update,lenofStock update,len_temp,newcolname
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.,9573,34,asdfsadf
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).,9573,39,asdfsadf
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).,9573,40,asdfsadf
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.,9573,34,asdfsadf
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.,9573,34,asdfsadf
...,...,...,...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf

In [80]:
df3.drop('test',axis=1,inplace=True)

In [81]:
df3

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update,lenofStock update,len_temp,newcolname
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.,9573,34,asdfsadf
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).,9573,39,asdfsadf
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).,9573,40,asdfsadf
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.,9573,34,asdfsadf
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.,9573,34,asdfsadf
...,...,...,...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).,9573,40,asdfsadf

In [83]:
df3.drop(columns=['lenofStock update','len_temp','newcolname'],axis=1,inplace=True)

In [84]:
df3

,Number reviews,Real price,Shipment,Delivery Date,How many time in past month,Stock update
0,101,$1.92,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,386,$1.93,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,"1,573",$2.90,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,9,$2.90,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"20,378",$3.14,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...
9568,11,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,5,None,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).

In [90]:
cols = []
for col in df3.columns:
    if col not in ['Real price','Delivery Date','Stock update']:
        cols.append(col)

In [91]:
cols

['Number reviews', 'Shipment', 'How many time in past month']

In [92]:
df3.drop(columns=cols,axis=1,inplace=True)

In [93]:
df3

     Real price Delivery Date                              Stock update
0         $1.92   Mon, Jun 19        Only 7 left in stock - order soon.
1         $1.93   Mon, Jun 19   Only 4 left in stock (more on the way).
2         $2.90   Mon, Jun 19  Only 16 left in stock (more on the way).
3         $2.90   Mon, Jun 19        Only 3 left in stock - order soon.
4         $3.14   Mon, Jun 19        Only 2 left in stock - order soon.
...         ...           ...                                       ...
9568       None   Mon, Jun 19  Only 17 left in stock (more on the way).
9569       None   Mon, Jun 19  Only 17 left in stock (more on the way).
9570       None   Mon, Jun 19  Only 17 left in stock (more on the way).
9571       None   Mon, Jun 19  Only 17 left in stock (more on the way).
9572       None   Mon, Jun 19  Only 17 left in stock (more on the way).

[9573 rows x 3 columns]

In [94]:
df

,Title,Price,Number reviews,Real price,Free days,Shipment,Delivery Date,How many time in past month,Stock update
0,Dorman 955-167 Driver Side Power Door Mirror f...,35,101,$1.92,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 7 left in stock - order soon.
1,CURT 51323 Quick Plug Electric Trailer Brake C...,19,386,$1.93,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 4 left in stock (more on the way).
2,HAMPTON PROD Keeper - 48” Carabiner Bungee Cor...,13,"1,573",$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 16 left in stock (more on the way).
3,"CR Brophy Machine Works RB34 1"" x 3/4"" Hitch B...",2,9,$2.90,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 3 left in stock - order soon.
4,"Ampper Blind Spot Mirror, 2"" Round HD Glass Fr...",8,"20,378",$3.14,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",50+ bought in past week,Only 2 left in stock - order soon.
...,...,...,...,...,...,...,...,...,...
9568,Warn 74924 (MTO) DRUM_WINCH_RT40,76,11,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9569,"Rugged Ridge 11580.10 Trailer Hitch, 2 inch; 0...",7,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9570,Gates 31633 OE Equivalent Fuel Tank Cap,71,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9571,BIG RED 2.5 Ton (5000 lb) Torin Low Profile Hy...,35,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).
9572,BIG RED ATRT2272CR Torin Manual Heavy Duty Han...,26,5,None,90 days FREE. Terms apply.,Yes,"Mon, Jun 19",10% off coupon Details,Only 17 left in stock (more on the way).